-- 収支カテゴリ。
-- ※ 認証導入時に user_id 列を追加できるよう、単純な構造にしておく。
create table categories (
    id         bigint generated by default as identity primary key,
    name       varchar(50) not null,
    type       varchar(20) not null,
    created_at timestamptz not null default now()
);

-- 収支記録。
create table transactions (
    id          bigint generated by default as identity primary key,
    type        varchar(20) not null,
    amount      bigint      not null,
    category_id bigint      not null references categories (id),
    occurred_on date        not null,
    memo        varchar(255),
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

create index idx_transactions_occurred_on on transactions (occurred_on);
create index idx_transactions_category_id on transactions (category_id);
